name: ensa-lost-found
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: dahbimoad/ENSA-Lost-Found--
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  routes:
  - path: /
  run_command: heroku-php-apache2 public/
  source_dir: /
databases:
- engine: MYSQL
  name: ensa-lost-found-db
  num_nodes: 1
  size: db-s-dev-database
  version: "8"
